import {
  Briefcase,
  Dumbbell,
  BookOpen,
  Heart,
  Home,
  Target,
  Coffee,
  Phone,
  Mail,
  Calendar,
  Clock,
  Star,
  Flag,
  Bookmark,
  Folder,
  FileText,
  Edit,
  Check,
  X,
  AlertCircle,
  Info,
  HelpCircle,
  Settings,
  User,
  Users,
  MessageCircle,
  Send,
  Image,
  Video,
  Music,
  Headphones,
  Mic,
  Camera,
  Map,
  Navigation,
  Globe,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Zap,
  Battery,
  Wifi,
  Bluetooth,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Printer,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Percent,
  Truck,
  Package,
  Box,
  Archive,
  Trash,
  RefreshCw,
  Download,
  Upload,
  Share,
  Link,
  ExternalLink,
  Copy,
  Scissors,
  Clipboard,
} from 'lucide-react';
import type { ReactNode } from 'react';

const iconComponents: Record<string, React.ComponentType<{ size?: number; className?: string }>> = {
  briefcase: Briefcase,
  dumbbell: Dumbbell,
  book: BookOpen,
  heart: Heart,
  home: Home,
  target: Target,
  coffee: Coffee,
  phone: Phone,
  mail: Mail,
  calendar: Calendar,
  clock: Clock,
  star: Star,
  flag: Flag,
  bookmark: Bookmark,
  folder: Folder,
  file: FileText,
  edit: Edit,
  check: Check,
  x: X,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,
  settings: Settings,
  user: User,
  users: Users,
  message: MessageCircle,
  send: Send,
  image: Image,
  video: Video,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  camera: Camera,
  map: Map,
  navigation: Navigation,
  globe: Globe,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  umbrella: Umbrella,
  zap: Zap,
  battery: Battery,
  wifi: Wifi,
  bluetooth: Bluetooth,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  printer: Printer,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  percent: Percent,
  truck: Truck,
  package: Package,
  box: Box,
  archive: Archive,
  trash: Trash,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  share: Share,
  link: Link,
  'external-link': ExternalLink,
  copy: Copy,
  scissors: Scissors,
  clipboard: Clipboard,
};

export function getTaskIcon(iconName: string, size: number = 16): ReactNode {
  const IconComponent = iconComponents[iconName] || Target;
  return <IconComponent size={size} />;
}

export function getProjectIcon(iconName: string, size: number = 16): ReactNode {
  return getTaskIcon(iconName, size);
}

export const availableIcons = Object.keys(iconComponents);
